wip: design v2
wethegit/react-modal pull request #7
Opened 2023-11-22 03:06 UTC by marlonmarcello

2023-11-22 20:40 UTC, marlonmarcello commented
I am thinking of changing `slug` to `hash`.

2023-11-23 18:18 UTC, andrewrubin requested changes
Great work @marlonmarcello , I dig the new setup. A few ideas and tweaks from me, below. One other thing which I cannot properly comment on — we should enforce `stylelint/order` on these CSS modules

Thanks, lmk if you want to chat about any of this!

2023-11-23 18:18 UTC, andrewrubin commented on src/lib/hooks/use-modal.ts
> +  slug?: string
I'm happy to change this to `hash`, as you suggested the other day, @marlonmarcello, if you like.

2023-11-23 20:22 UTC, marlonmarcello commented on src/lib/components/modal-backdrop/modal-backdrop.module.scss
> +  background-color: rgb(0 0 0 / 80%);
Don't really see what's the benefit @andrewrubin 
Someone changing this component would have to:
```
.customBackdrop {
  background-color: red;
}

/* OR */

.customBackdrop {
  --backdrop-color: red
}
```

It's pretty much the exact same thing and the user don't have to know about the CSS Variable.

2023-11-23 20:23 UTC, marlonmarcello commented on src/lib/components/modal-inner/modal-inner.module.scss
> +  position: fixed;
Awesome idea!

2023-11-23 20:24 UTC, marlonmarcello commented on src/lib/hooks/use-modal.ts
> +    window.addEventListener("keyup", onKeyUp)
@andrewrubin it calls `handleClose` which takes care of that 🦄

2023-11-23 20:24 UTC, marlonmarcello commented on src/main.module.css
Thank u!

2023-11-23 20:25 UTC, marlonmarcello commented on src/lib/hooks/use-modal.ts
> +  transitionDuration?: number
That's a great shout

2023-11-23 20:25 UTC, marlonmarcello commented on src/lib/hooks/use-modal.ts
> +  slug?: string
Think I will then!

2023-11-23 21:23 UTC, marlonmarcello commented on src/lib/hooks/use-modal.ts
> +  transitionDuration?: number
Andrew, I think I am going to leave it out for now and create a separate ticket for that. That way we add it if we actually see a need for it. We did away without this far so it seems like that will be extra complexity without any usage.

2023-11-23 22:28 UTC, andrewrubin commented on src/lib/hooks/use-modal.ts
> +  transitionDuration?: number
I think the current solution we use is the `onOpenStart` or `onCloseStart` function, if I recall. This allows us to have finer control over when to resolve the modal as being fully closed or open, if we want to.

Maybe exposing the MODAL_STATES here solves that though?

2023-11-24 01:58 UTC, marlonmarcello commented on src/lib/hooks/use-modal.ts
> +  transitionDuration?: number
I did expose the `state` on the return. But still, do we use those?

2023-11-24 02:12 UTC, andrewrubin commented on src/lib/hooks/use-modal.ts
> +  transitionDuration?: number
Nah I don't think we really do :) But we totally could… tbh I'm just thinking out loud at this point. 

Interesting idea though, for example, maybe sometime down the road we decide we want an option to specify exactly when these things finished opening and closing, _outside_ the realm of CSS or setTimeouts. Silly example:

```jsx
async function handleOpen () {
  await loadTwentyGIFsFromGiphy()
  dispatchState(MODAL_STATES.OPENED)
}

<Modal onOpen={handleOpen} />
```

Could be a fun problem to solve. But not necessary right now I don't think.

2023-11-24 02:16 UTC, andrewrubin commented on src/lib/hooks/use-modal.ts
> +    window.addEventListener("keyup", onKeyUp)
Chatted over Slack –  this still needs to remove the hash on Esc, so we discussed moving all hash-related logic into `handleOpen` and `handleClose`

2023-11-24 02:34 UTC, marlonmarcello commented on src/lib/hooks/use-modal.ts
> +  transitionDuration?: number
We should look into how react transition group and framer do this, having variables for each in/out/in-between sounds so inneficient

Maybe we do that now, with this new major @andrewrubin

2023-11-24 02:35 UTC, marlonmarcello commented on src/lib/hooks/use-modal.ts
> +    window.addEventListener("keyup", onKeyUp)
Tomorrow I am going to see if I can reduce the amount of useEffects and callback and update this

2023-11-24 05:50 UTC, andrewrubin commented on src/lib/hooks/use-modal.ts
> +  transitionDuration?: number
As far as my experience with RTG goes, I know they use four different states, sort of similar: entering, entered, exiting, and exited. Those are passed down through a state argument to `children(state)` if I recall correctly. 

As for framer, it's clean in that they abstract a lot away, and allow you to just write your "shown" and "hidden" states and define the transitions between them... but I don't like the api that much, it feels like, at least **for our purposes**, too much of an abstraction, when we could easily use simple CSS for things.

2023-11-24 21:12 UTC, marlonmarcello commented on src/lib/hooks/use-modal.ts
> +  transitionDuration?: number
Kay. I removed this entirely. The modal shouldn't have to take care of animation like this. I am moving this responsibility to a [hook](https://github.com/wethegit/component-library/pull/63).

2023-11-24 21:12 UTC, marlonmarcello commented
All done now @andrewrubin

2023-11-28 18:12 UTC, marlonmarcello commented
Converting it to a Draft while we wait for [hooks v2](https://github.com/wethegit/react-hooks/pull/6)

2023-11-28 22:25 UTC, andrewrubin approved these changes

2023-11-28 22:29 UTC, merged